### ISSUE TITLE
Locale and creator

### ISSUE THREAD

**Issue by CFanselow** [ajnyga/objectsForReview#4]
Hi @ajnyga, 

1. in https://github.com/ajnyga/objectsForReview/blob/stable-3-1-2/locale/de_DE/emailTemplates.xml#L14

"en_US" should be changed to "de_DE". 

2. I could not save the data in submission workflow -> metadata. I works if I add

		$objectForReview->setCreator("manager");

to https://github.com/ajnyga/objectsForReview/blob/stable-3-1-2/controllers/grid/form/ObjectsForReviewForm.inc.php#L142

Regards, 
Carola

**Comment by ajnyga** [comment]
Hi, is this specifically for 3.1.2?

**Comment by CFanselow** [comment]
I didn't test it on other versions.

**Comment by ajnyga** [comment]
These should be all fixed in the latest version, some of it already in the last version
